name: sublime_log_example
description: Demonstrates how to use the sublime_log plugin.
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  sublime_log:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=1.10.0"