name: sublime_log
description: Flutter package which manages the logs message, view or share to other.
version: 1.0.6
homepage: https://github.com/tusaamf/sublime_log

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=3.0.1 <4.0.0"